version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "music-library"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b9imfm9sqnqr"
s3_prefix = "music-library"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
