# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
    music-library

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
    - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
    # Each Lambda function is defined by properties:
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

    getLibraryItemsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/music-library.getLibraryItems
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Lambda for retrieving all library items.
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                GetLibraryItems:
                    Type: Api
                    Properties:
                        Path: /libraryItems
                        Method: get

    createLibraryItemFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/music-library.createLibraryItem
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Lambda for creating a library item.
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                GetLibraryItems:
                    Type: Api
                    Properties:
                        Path: /libraryItems
                        Method: post

    patchLibraryItemFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/music-library.patchLibraryItem
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Lambda for modifying an existing library item.
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                PatchLibraryItem:
                    Type: Api
                    Properties:
                        Path: /libraryItems/{itemId}
                        Method: patch

    getLibraryItemFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/music-library.getLibraryItem
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Lambda for retrieving a library item.
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                GetLibraryItem:
                    Type: Api
                    Properties:
                        Path: /libraryItems/{itemId}
                        Method: get

    MusicLibraryTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: "itemId"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "itemId"
                  KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: "5"
                WriteCapacityUnits: "5"
            TableName: "music-library-items"

Outputs:
    getLibraryItemsFunction:
        Description: "Get Library Items Lambda Function ARN"
        Value: !GetAtt getLibraryItemsFunction.Arn
